<?php

/**
 * BaseComments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $object_id
 * @property string $text
 * @property boolean $negative
 * @property sfGuardUser $sfGuardUser
 * @property Objects $Objects
 * 
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method integer     getObjectId()    Returns the current record's "object_id" value
 * @method string      getText()        Returns the current record's "text" value
 * @method boolean     getNegative()    Returns the current record's "negative" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Objects     getObjects()     Returns the current record's "Objects" value
 * @method Comments    setUserId()      Sets the current record's "user_id" value
 * @method Comments    setObjectId()    Sets the current record's "object_id" value
 * @method Comments    setText()        Sets the current record's "text" value
 * @method Comments    setNegative()    Sets the current record's "negative" value
 * @method Comments    setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method Comments    setObjects()     Sets the current record's "Objects" value
 * 
 * @package    reelty
 * @subpackage model
 * @author     BulgakowS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComments extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comments');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('object_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('text', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('negative', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Objects', array(
             'local' => 'object_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}