<?php

/**
 * BaseSubj_of_law
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property sfGuardUser $sfGuardUser
 * 
 * @method string      getName()        Returns the current record's "name" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Subj_of_law setName()        Sets the current record's "name" value
 * @method Subj_of_law setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    reelty
 * @subpackage model
 * @author     BulgakowS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubj_of_law extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subj_of_law');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'id',
             'foreign' => 'subj_of_law_id'));
    }
}