<?php

/**
 * BaseActions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Objects
 * 
 * @method string              getName()    Returns the current record's "name" value
 * @method Doctrine_Collection getObjects() Returns the current record's "Objects" collection
 * @method Actions             setName()    Sets the current record's "name" value
 * @method Actions             setObjects() Sets the current record's "Objects" collection
 * 
 * @package    reelty
 * @subpackage model
 * @author     BulgakowS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('actions');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Objects', array(
             'local' => 'id',
             'foreign' => 'actions_id'));
    }
}