<?php

/**
 * ActionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Actions');
    }

//    public function addObjectsByActionQuery(Doctrine_Query $q = null)
//    {
//        if (is_null($q))
//        {
//            $q = Doctrine_Query::create()
//            ->from('Objects o');
//        }
//
//        $alias = $q->getRootAlias();
//
//        $q->addOrderBy($alias . '.updated_at DESC');
//        
//        return $q;
//    }
    
    public static function getAllActions(){
        return Doctrine::getTable('Actions')
              ->createQuery('a')
              ->orderBy('a.name ASC')
              ->execute();
    }
}