<?php

/**
 * Actions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    reelty
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Actions extends BaseActions
{
    public function getObjectsByActionQuery($act)
    {
        $q = Doctrine_Query::create()
            ->from('Objects o')
            ->where('o.actions_id = ?', $act);

        return Doctrine_Core::getTable('Actions')->addObjectsByActionQuery($q);
    }
}
