<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    reelty
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Category extends BaseCategory
{
    public function __toString()
    {
        return sprintf('%s', $this->getName() );
    }

    public function getObjectsByCategoryQuery($cat)
    {
        $q = Doctrine_Query::create()
            ->from('Objects o')
            ->where('o.category_id = ?', $cat);

        return Doctrine_Core::getTable('Category')->addObjectsByCategoryQuery($q);
    }
}
