<?php

/**
 * ObjectsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObjectsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObjectsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Objects');
    }

    public static function getObjectsByCategoryId( $cat )
    {
        $q = Doctrine_Query::create()
            ->from('Objects o')
            ->where('o.category_id = ?', $cat);

        return $q->execute();
    }
    
    
}