<?php

/**
 * ObjectsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObjectsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObjectsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Objects');
    }

    public static function getObjectsByCategoryId( $cat )
    {
        $q = self::getFullObjectsQuery();
        $q->where('o.category_id = ?', $cat);

        return $q;
    }
    
    public static function getObjectsByActionsId( $act )
    {
        $q = self::getFullObjectsQuery();
        $q->where('o.actions_id = ?', $act);

        return $q;
    }
    
    public static function getFullObjectsQuery(){
        return $q = Doctrine_Core::getTable('Objects')->createQuery('o')
                    ->where('o.avaible = true')
                    ->leftJoin('o.Actions a')
                    ->leftJoin('o.Category c')
                    ->orderBy('o.updated_at DESC');
    }
    
    
    
}