<?php

/**
 * Subj_of_lawTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Subj_of_lawTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Subj_of_lawTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Subj_of_law');
    }
}