<?php

/**
 * Subj_of_law
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    reelty
 * @subpackage model
 * @author     BulgakowS
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Subj_of_law extends BaseSubj_of_law
{
}
