generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Objects
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          objects
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  
        display: [id, user_id]
      form:    ~
      edit:    ~
      new:     ~
